services:
  consul-server:
    image: hashicorp/consul:latest
    container_name: consul-server
    volumes:
      - ./consul/config/:/consul/config/
      - ./consul/data:/consul/data
      - ./consul/config/certs:/etc/consul.d/certs
    command: ["/consul/config/start-consul.sh"]
    healthcheck:    
      test:
        [
          "CMD",
          "curl",
          "-f",
          "https://127.0.0.1:8501/v1/status/leader",
          "--cacert",
          "/etc/consul.d/certs/dc1.consul-agent-ca.pem",
          "--cert",
          "/etc/consul.d/certs/dc1-server-consul-0.pem",
          "--key",
          "/etc/consul.d/certs/dc1-server-consul-0-key.pem",
        ] 
      interval: 10s
      timeout: 10s
      retries: 5
    restart: unless-stopped

  vault-main-server:
    image: hashicorp/vault:latest
    ports:
      - "8200:8200"
    volumes:
      - ./main-vault:/vault
      - ./main-vault/certs:/vault/config/certs
      - ./main-vault/certs/vault.crt:/etc/certs/vault.crt
      - ./main-vault/certs/vault.key:/etc/certs/vault.key
      - ./main-vault/certs/vault-ca.crt:/etc/certs/vault-ca.crt
    command: ["vault", "server", "-config=/vault/config/vault-config.hcl"]
    cap_add:
      - IPC_LOCK
    depends_on:
      consul-server:
        condition: service_healthy
    env_file: 
      - ./main-vault/.env
    restart: unless-stopped


